# Generated by Django 3.1.5 on 2021-02-06 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20210206_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='city',
        ),
    ]
